version: '3'


services:

  nginx:
    restart: always
    image: nginx:1.17
    depends_on:
      - ctfd
    hostname: ctf.staszic.waw.pl
    volumes:
      - ./ssl:/etc/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./docker-volumes/nginx/logs:/var/log
    ports:
      - 94.240.45.212:80:8000
      - 94.240.45.212:443:8443
    networks:
      - default
      - nginx

  ctfd_db:
    environment:
      - MYSQL_ROOT_PASSWORD=BrDHwg3uyemzeq2cYT4FT1PrJrdfajNg
      - MYSQL_USER=igtGLLwstfLo62jgcpxcj0Yc1gcXWFhr
      - MYSQL_PASSWORD=tONTlJQQr9GqClr3ouikNdpKDIxvqhyI
      - MYSQL_DATABASE=ctfd

  ctfd:
    environment:
      - DATABASE_URL=mysql+pymysql://igtGLLwstfLo62jgcpxcj0Yc1gcXWFhr:tONTlJQQr9GqClr3ouikNdpKDIxvqhyI@ctfd_db:3306/ctfd
      - REDIS_URL=redis://ctfd_cache:6379
      - WORKERS=1
      - UPLOAD_FOLDER=/var/uploads
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=/var/log/gunicorn.access.log
      - ERROR_LOG=/var/log/gunicorn.error.log
      - USE_SSL=false
      - REVERSE_PROXY=true
    expose:
      - 8000
    ports: []
    networks:
      - nginx
      - ctfd_db
      - ctfd_cache


networks:
  nginx:
    internal: true
