version: '3.4'


services:

  nginx:
    restart: always
    build: ./nginx/
    healthcheck:
      test: CMD /healthcheck
      interval: 2m
      timeout: 6s
      retries: 3
    depends_on:
      - ctfd
    hostname: ctf.staszic.waw.pl
    volumes:
      - ./ssl:/etc/ssl:ro
      - ./docker-volumes/nginx/logs:/var/log
    ports:
      - 94.240.45.212:80:8000
      - 94.240.45.212:443:8443
    networks:
      - default
      - proxy

  ctfd_db:
    environment:
      - MYSQL_ROOT_PASSWORD=BrDHwg3uyemzeq2cYT4FT1PrJrdfajNg
      - MYSQL_USER=igtGLLwstfLo62jgcpxcj0Yc1gcXWFhr
      - MYSQL_PASSWORD=tONTlJQQr9GqClr3ouikNdpKDIxvqhyI
      - MYSQL_DATABASE=ctfd

  ctfd:
    environment:
      - DATABASE_URL=mysql+pymysql://igtGLLwstfLo62jgcpxcj0Yc1gcXWFhr:tONTlJQQr9GqClr3ouikNdpKDIxvqhyI@ctfd_db:3306/ctfd
      - REDIS_URL=redis://ctfd_cache:6379
      - WORKERS=1
      - UPLOAD_FOLDER=/var/uploads
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=/var/log/gunicorn.access.log
      - ERROR_LOG=/var/log/gunicorn.error.log
      - USE_SSL=false
      - REVERSE_PROXY=true
    expose:
      - 8000
    ports: []
    networks:
      - proxy
      - ctfd_db
      - ctfd_cache

  text_flag:
    restart: always
    build: ./tasks/text-flag/
    healthcheck:
      test: CMD /healthcheck
      interval: 10m
      timeout: 10s
      retries: 3
    command: tail -f


networks:
  proxy:
    internal: true
