version: '3.4'


services:

  nginx:
    restart: always
    build: ./nginx/
    healthcheck:
      test: [CMD, /healthcheck]
      interval: 2m
      timeout: 6s
      retries: 3
    depends_on:
      - ctfd
    hostname: ctf.staszic.waw.pl
    volumes:
      - ./docker-volumes/nginx/logs:/var/log
    ports:
      - 94.240.45.212:80:8000
      - 94.240.45.212:443:8443
    networks:
      - default
      - proxy

  ctfd-db:
    environment:
      - MYSQL_ROOT_PASSWORD=BrDHwg3uyemzeq2cYT4FT1PrJrdfajNg
      - MYSQL_USER=igtGLLwstfLo62jgcpxcj0Yc1gcXWFhr
      - MYSQL_PASSWORD=tONTlJQQr9GqClr3ouikNdpKDIxvqhyI

  ctfd:
    environment:
      - DATABASE_URL=mysql+pymysql://igtGLLwstfLo62jgcpxcj0Yc1gcXWFhr:tONTlJQQr9GqClr3ouikNdpKDIxvqhyI@ctfd-db:3306/ctfd
    expose:
      - 8000
    networks:
      - proxy
      - ctfd-db
      - ctfd-cache

  text-flag:
    restart: always
    build: ./tasks/text-flag/
    healthcheck:
      test: [CMD, /healthcheck]
      interval: 10m
      timeout: 10s
      retries: 3
    command: [tail, -f]

  confucius:
    ports:
      - 94.240.45.212:1337:1330

  confucius2:
    ports:
      - 94.240.45.212:1338:1330

  secure-random:
    ports:
      - 94.240.45.212:1339:1330

  editor:
    ports:
      - 94.240.45.212:1340:9000


networks:
  proxy:
    internal: true
