version: '3.4'


services:

  ctfd_db:
    restart: always
    image: mariadb:10.4.12
    # This command is required to set important mariadb defaults
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=1]
    environment:
      - MYSQL_ROOT_PASSWORD=ctfd
      - MYSQL_USER=ctfd
      - MYSQL_PASSWORD=ctfd
      - MYSQL_DATABASE=ctfd
    volumes:
      - ./docker-volumes/ctfd_db/logs:/var/log
      - ./docker-volumes/ctfd_db/mysql:/var/lib/mysql
    expose:
      - 3306
    networks:
      - ctfd_db

  ctfd_cache:
    restart: always
    image: redis:4
    volumes:
      - ./docker-volumes/ctfd_cache/logs:/var/log
      - ./docker-volumes/ctfd_cache/data:/data
    expose:
      - 6379
    networks:
      - ctfd_cache

  ctfd:
    restart: always
    build: ./CTFd/
    depends_on:
      - ctfd_db
      - ctfd_cache
    user: root
    environment:
      - DATABASE_URL=mysql+pymysql://ctfd:ctfd@ctfd_db:3306/ctfd
      - REDIS_URL=redis://ctfd_cache:6379
      - WORKERS=1
      - UPLOAD_FOLDER=/var/uploads
      - LOG_FOLDER=/var/log/CTFd
      - ACCESS_LOG=/var/log/gunicorn.access.log
      - ERROR_LOG=/var/log/gunicorn.error.log
      - USE_SSL=false
      - REVERSE_PROXY=true
    volumes:
      - ./CTFd:/opt/CTFd:ro
      - ./docker-volumes/ctfd/logs:/var/log
      - ./docker-volumes/ctfd/uploads:/var/uploads
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - default
      - ctfd_db
      - ctfd_cache

  confucius:
    restart: always
    build: ./tasks/confucius-tradition-1/
    ports:
      - 127.0.0.1:1337:1330
    networks:
      - default

  confucius2:
    restart: always
    build: ./tasks/confucius-tradition-2/
    ports:
      - 127.0.0.1:1338:1330
    networks:
      - default

  secure-random:
    restart: always
    build: ./tasks/secure-random/
    ports:
      - 127.0.0.1:1339:1330
    networks:
      - default

  editor:
    restart: always
    build: ./tasks/editor/
    privileged: true
    ports:
      - 127.0.0.1:1340:9000
    networks:
      - default


networks:
  default:
  ctfd_db:
    internal: true
  ctfd_cache:
    internal: true
